import Footer from "@/components/Layout/Footer";
import Script from "next/script";
import "./global.css";

export const metadata = {
	title: "Super Simple Recipes",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Script src="http://localhost:8097" />
			<body className="scroll-smooth">
				<main className="min-h-screen prose mx-auto">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
