import Footer from "@/components/Layout/Footer";
import { Analytics } from '@vercel/analytics/react';
import Script from "next/script";
import "./global.css";

export const metadata = {
	title: "Super Simple Recipes",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Script src="http://localhost:8097" />
			<body className="scroll-smooth">
				<main className="mx-auto min-h-screen prose">{children}</main>
				<Footer />
			</body>
			<Analytics />
		</html>
	);
}
